### ISSUE TITLE
[spoteus] Segmention Fault in generating spot.l

### ISSUE THREAD

**Issue by mqcmd196** [k-okada/jsk_robot#118]
- Environment
  - Ubuntu 22.04

repos
```yaml
repositories:
  jsk-ros-pkg/jsk_3rdparty:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_3rdparty
    version: master
  jsk-ros-pkg/jsk_common:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_common
    version: master
  jsk-ros-pkg/jsk_model_tools:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_model_tools
    version: master
  jsk-ros-pkg/jsk_pr2eus:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_pr2eus
    version: master
  jsk-ros-pkg/jsk_recognition:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_recognition
    version: master
  jsk-ros-pkg/jsk_robot:
    type: git
    url: https://github.com/k-okada/jsk_robot
    version: spot_arm
  jsk-ros-pkg/jsk_visualization:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_visualization
    version: master
  k-okada/spot_ros-arm:
    type: git
    url: https://github.com/k-okada/spot_ros-arm
    version: arm

```

When I build the spoteus, it segfaults like

```
❯ roscd spoteus && mkdir build && cd build && cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using CATKIN_DEVEL_PREFIX: /home/obinata/ros/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spoteus/build/devel
-- Using CMAKE_PREFIX_PATH: /home/obinata/ros/catkin_ws/devel;/opt/ros/one
-- This workspace overlays: /home/obinata/ros/catkin_ws/devel;/opt/ros/one
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/obinata/ros/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spoteus/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- set EUSDIR to /opt/ros/one/share/euslisp/jskeus/eus
-- set ARCHDIR to Linux64
-- [roseus.cmake] loading roseus.cmake from spoteus
-- [roseus.cmake] roseus 1.7.5
-- [roseus.cmake] jskeus 1.2.5
-- [roseus.cmake] euslisp 9.29.0
-- [roseus.cmake] geneus 3.0.0
-- [roseus.cmake] genmsg 0.5.16
-- [roseus.cmake] message_generation Requires: gencpp;geneus;gennodejs;genlisp;genmsg;genpy
spot_urdf: /home/obinata/ros/catkin_ws/src/k-okada/spot_ros-arm/spot_description/urdf
urdf_to_collada:
collada2eus: /home/obinata/ros/catkin_ws/devel/.private/euscollada/lib/euscollada/collada2eus
-- Configuring done
-- Generating done
-- Build files have been written to: /home/obinata/ros/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spoteus/build
❯ m -j
[ 50%] Generating ../spot.l
/home/obinata/ros/catkin_ws/devel/.private/euscollada/lib/euscollada/collada2eus spot.urdf spot.l
;; Input file is: /home/obinata/ros/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spoteus/spot.urdf
;; Config file is:
;;   /home/obinata/ros/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spoteus/spot.yaml
;; Output file is: /home/obinata/ros/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_spot_robot/spoteus/spot.l
;; robot_name is: spot
lfleg@5
rfleg@9
lrleg@13
rrleg@17
arm@21
hand@28
[WARN][1744169266.756897759][${node}:ros.euscollada]: read sensor settings from yaml
make[2]: *** [CMakeFiles/compile_spot.dir/build.make:76: ../spot.l] Segmentation fault (core dumped)
make[2]: *** Deleting file '../spot.l'
make[1]: *** [CMakeFiles/Makefile2:2084: CMakeFiles/compile_spot.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
